name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy through SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/hms-hotel-erp
            git pull origin main

            cd backend
            source .venv/bin/activate || true
            pip install -r requirements.txt

            sudo supervisorctl reread
            sudo supervisorctl update
            sudo supervisorctl restart erp-api

            cd ../frontend
            npm install --legacy-peer-deps
            npm run build

            sudo supervisorctl restart hms-frontend

            sudo supervisorctl status erp-api
            sudo supervisorctl status hms-frontend
